homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirmation/', views.confirmation, name='confirmation'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
    name = models.CharField(max_length = 255)
    status = models.CharField(max_length = 255)

    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name', 'status']
        labels = {'name': 'Name', 'status': 'Status'}
        widgets = {'name': forms.TextInput(), 'status': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Status
from .forms import StatusForm

def index(request):
    status = Status.objects.all()

    if (request.method == 'POST'):
        form = StatusForm(request.POST)
        if (form.is_valid()):
            new = Status()
            new.name = form.cleaned_data['name']
            new.status = form.cleaned_data['status']
            response = {'name':new.name, 'status':new.status}
            return render(request, 'confirmation.html', response)
    else:
        form = StatusForm()
    
    response = {'status':status, 'form':form}
    return render(request, 'index.html', response)

def confirmation(request):
    if (request.method == 'POST'):
        form = StatusForm(request.POST)
        if (form.is_valid()):
            new = Status()
            new.name = form.cleaned_data['name']
            new.status = form.cleaned_data['status']
            new.save()
            return redirect('/')
    else:
        form = StatusForm()

    response = {'form':form}
    return render(request, 'confirmation.html', response)

homepage/templates/confirmation.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/CSS">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Confirm</title>
</head>

<body>
    <div style="align-content: center;">
        <br><br><br>
        <h1>Confirmation</h1>
        <form action="{% url 'homepage:confirmation' %}" method='POST'>
            {% csrf_token %}
            <div class="form-row">
                <div class="col-sm"></div>
                <div class="form-group col-sm-8">
                    <label for="name" class="form-label">Name: {{ name }}</label>
                    <input class="form-control" id="name" type="hidden" name="name" value="{{ name }}">
                    <br>
                    <label for="status" class="form-label">Status: {{ status }}</label>
                    <input class="form-control" id="status" type="hidden" name="status" value="{{ status }}">
                </div>
                <div class="col-sm"></div>
            </div>
            <div class="row">
                <button type="submit" class="btn submit" name="save">Save</button>
                <a class="btn submit" href="{% url 'homepage:index' %}" role="button" name="back">Back</a>
            </div>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

homepage/templates/index.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/CSS">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Hello</title>
</head>

<body>
    <div style="align-content: center;">
        <br><br><br>
        <h1>Hello, how are you?</h1>
        <form method='POST'>
            {% csrf_token %}
            <div class="form-row">
                <div class="col-sm"></div>
                <div class="form-group col-sm-8">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input class="form-control" id="name" type="text" name="name" maxlength="255" required placeholder="Please enter your name">
                    </div>

                    <div class="form-group">
                        <label for="name">Status</label>
                        <input class="form-control" id="status" type="text" name="status" maxlength="255" required placeholder="Please enter your status">
                    </div>
                </div>
                <div class="col-sm"></div>
            </div>
            <div class="row">
                <input type="submit" class="btn submit" id="submit" value="Submit">
            </div>
            <br><br>
            <div>
                <div class="text-center">
                    <p class="status">status</p>
                    <center><div style="width: 25%; height: 3px; background-color: #1A3852;"></div></center>
                    <div class="container">
                        <br>
                
                        <table class="table">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col" style="color: #243370">Name</th>
                                <th scope="col" style="color: #243370">Status</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for i in status %}
                                <tr>
                                    <td style="text-align: center;">{{ i.name }}</td>
                                    <td style="text-align: center;" name="challenge" class="challenge">{{ i.status }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <br>
                    <div>
                        <button class="btn submit" onclick=changeColor() name="challengeButton">Change Status Color</button>
                    </div>    
                </div>
            </div>
        </form>
    </div>
    <script>
        function changeColor() {
            var elements = document.getElementsByClassName("challenge");
            for (var i = 0; i < elements.length; i++) {
                elements[i].style.color = "#243370";
            }
        }
    </script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>